
spring:
  cloud:
    config:
      server:
        git:
#          连接远程的配置仓库
          uri: https://github.com/tsuixh/config-server/tree/dev/config
  application:
    name: config-server
server:
  port: 8888
